<a href="https://colab.research.google.com/github/ibk25244/su-ai/blob/master/4_numpy_tasting_sol.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

- - -

<font size=6 color='royalblue'>넘파이 아주 살짝 맛보기</font>

<font size=5 color='forestgreen'>NumPy Tasting</font> 

* * *

**<font size=4>박 진 수</font>** 교수  
Intelligent Data Semantics Lab  
Seoul National University

- - -

>[넘파이(NumPy)란?](#scrollTo=ehYqbxznRBTP)

>[관련 모듈 불러오기](#scrollTo=XVNjbKUTRBTQ)

>[넘파이 배열(array)](#scrollTo=orxP9aenRBTe)

>>[파이썬 리스트와의 차이](#scrollTo=8AY8gHsGRBTf)

>>>[1차원 더하기 연산](#scrollTo=qSMaMQdMRBTh)

>>>[2차원 더하기 연산](#scrollTo=pedzf7gfRBT0)

>>>[1차원 곱하기 연산](#scrollTo=hH90bhphRBUF)

>>>[2차원 곱하기 연산](#scrollTo=fXLjuN-ZRBUX)

>[배열 생성](#scrollTo=zkR4NJLKRBUg)

>>[array() 함수](#scrollTo=2CQxG5MvRBUg)

>>>[1차원 배열](#scrollTo=6RsriuMqRBUh)

>>>[다차원 배열](#scrollTo=c-FuzCILRBU1)

>>[arange() 함수](#scrollTo=yutd2ymRRBVB)

>>[내장함수](#scrollTo=hxn0X308RBVc)

>>>[zeros() 함수](#scrollTo=4yd5rSJvRBVe)

>>>[eye() 함수](#scrollTo=Z_ceX5H3RBWN)

>>>[diag() 함수](#scrollTo=paHlzA5BRBYO)

>>>[random.random() 함수](#scrollTo=am0zAwuURBZ0)

>>>[random.randint() 함수](#scrollTo=L9TdKyxsRBaF)

>>>[Lab: 랜덤 벡터 생성과 정렬](#scrollTo=VNn7NfftRBaT)

>[배열 자료형](#scrollTo=__YEqWHDRBaa)

>>[형변환 메소드](#scrollTo=Q7oiuSMNRBae)

>[배열의 차원](#scrollTo=ITuHmWviRBan)

>>[차원(rank) : ndim](#scrollTo=oRo-VAxwRBan)

>>[차원 형태 : shape](#scrollTo=am5mmT34RBaq)

>>[차원 변경 : reshape()](#scrollTo=S8SQChx8RBa7)

>>[Lab: 벡터를 행렬로 변환하기](#scrollTo=9VykEHmSRBbK)

>>[Lab: 대각행렬(diagonal matrix)](#scrollTo=Kop8dmB_RBbO)

>[기본 연산](#scrollTo=GJEpEPywRBbS)

>[행렬 연산](#scrollTo=Y9CCW4NIRBbu)

>>[행렬 합 : numpy.sum()](#scrollTo=cJ0SU5hgRBbv)

>>[내적 및 행렬 곱 : numpy.dot()](#scrollTo=tXUFFtR-RBb0)

>>>[곱하기 연산 비교](#scrollTo=OmoFWdUnRBcB)

>>[행렬의 전치 연산](#scrollTo=8kmX-kQIRBcP)

>[넘파이 배열 함수](#scrollTo=v451zTPzRBcW)

>>[Lab: 행렬 정규화(normalization)](#scrollTo=MBK5pKbnRBcn)

>[THE END](#scrollTo=xIwmPTD8RBcq)



# 넘파이(NumPy)란?

계산과학(computation science)분야에 자주 활용되는 파이썬 라이브러리다.
- 고성능의 다차원 배열(array) 객체와 이를 다룰 수 있는 다양한 도구를 지원한다.
    - Numpy의 내부가 상당 부분 C나 포트란으로 작성되어 있어 실행 속도도 꽤 빠르다.
- 기본적으로 배열(array)이라는 자료를 생성하고 이를 바탕으로 인덱싱 및 연산 처리 등을 편리하게 수행한다.
    - 난수생성, 푸리에변환, 행렬연산, 간단한 기술통계 분석 정도는 가능하지만 주로 scipy, pandas, matplotlib 등 다른 파이썬 패키지와 함께 쓰이는 경우가 많다.
- 문법이나 구동 방식이 MATLAB과 유사하다.
- Documentation
    - <https://docs.scipy.org/doc/> 

# 관련 모듈 불러오기

**import numpy**로 numpy를 불러와서 사용해야 한다.
- 주로 **import numpy as np**로 numpy를 불러와서, 짧게 *np*로 사용하는 경우가 많다.

In [ ]:
import numpy  # as np

# 버전을 확인한다.
print('NumPy version...:', numpy.__version__)  

NumPy version...: 1.18.4


# 넘파이 배열(array)

- 넘파이(NumPy)의 핵심적인 객체이다.
- 배열은 "동일한 자료형을 가지는 값들이 격자판 형태로 있는 것"이다.
- 파이썬의 리스트(list)와 거의 비슷하나 배열은 동일한 자료형만 들어가야 한다는 차이가 있다.
- 사용 방법도 리스트와 유사하나 특성과 활용 가능한 함수 등이 다르다.
- 다차원(n-dimensional) 배열로 확장이 가능하다.

## 파이썬 리스트와의 차이

<font style='font-weight: bold; font-size: 115%'>NumPy array는 다차원 배열(matrix) 연산에 유용한다.</font>

### 1차원 더하기 연산

In [ ]:
# --- 1차원 
# 파이썬 1차원 리스트
L = list(range(1, 6)) 

# 넘파이 1차원 배열
arr = numpy.array(L)  

print(L)
print(arr)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [ ]:
# --- 1차원 더하기 연산
# > L = [1, 2, 3, 4, 5]
# > arr = [1 2 3 4 5]
print(L + [10])       # 파이썬 리스트   
print(arr + 10)       # 넘파이 배열  

[1, 2, 3, 4, 5, 10]
[11 12 13 14 15]


In [ ]:
# --- 1차원 더하기 연산
# > L = [1, 2, 3, 4, 5]
# > arr = [1 2 3 4 5]
print(L + L)        # 파이썬 리스트   
print(arr + arr)    # 넘파이 배열  

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]


In [ ]:
# --- 만약 리스트로 넘파이 배열과 같은 계산을 하려면...
# > arr = [1 2 3 4 5]
# > arr + arr => [2 4 6 8 10]
# > L = [1, 2, 3, 4, 5]
alist = []
for i in L:
  alist.append(i + i)
else:
  print(alist)

[2, 4, 6, 8, 10]


In [ ]:
# --- 리스트 축약으로 하면...
# > arr = [1 2 3 4 5]
# > arr + arr => [2 4 6 8 10]
# > L = [1, 2, 3, 4, 5]
[(i + i) for i in L]

[2, 4, 6, 8, 10]

### 2차원 더하기 연산

In [ ]:
# --- 2차원 
# 파이썬 2차원 리스트
L2 = [list(range(1, 6)), list(range(6, 11))]  

# 넘파이 2차원 배열
arr2 = numpy.arange(1, 11).reshape(2, 5) 

print(L2)
print(arr2)

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
# --- 2차원 더하기 연산
# > L2 = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
# > arr2 = [[1 2 3 4 5] [6 7 8 9 10]]
print(L2 + L2)        # 파이썬 리스트
print(arr2 + arr2)    # 넘파이 배열

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
[[ 2  4  6  8 10]
 [12 14 16 18 20]]


In [ ]:
# --- 만약 리스트로 넘파이 배열과 같은 계산을 하려면...
# > arr2 = [[1 2 3 4 5] [6 7 8 9 10]]
# > arr2 + arr2 => [[2 4 6 8 10] [12 14 16 18 20]]
# > L2 = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
list2 = []
for row in L2:
  tmp = []
  for column in row:
    tmp.append(column + column)
  else:
    list2.append(tmp)
else:
  print(list2)  

[[2, 4, 6, 8, 10], [12, 14, 16, 18, 20]]


In [ ]:
# --- 리스트 축약으로 하면...
# > arr2 = [[1 2 3 4 5] [6 7 8 9 10]]
# > arr2 + arr2 => [[2 4 6 8 10] [12 14 16 18 20]]
# > L2 = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
[[column + column for column in row] for row in L2]  

[[2, 4, 6, 8, 10], [12, 14, 16, 18, 20]]

In [ ]:
# --- (NOTE)
x = [[1, 2, 3], [1, 2, 3]]
[[number + 1 for number in group] for group in x]

[[2, 3, 4], [2, 3, 4]]

### 1차원 곱하기 연산

In [ ]:
# --- (주의)
print(L * L)

TypeError: ignored

In [ ]:
# --- 1차원 곱하기 연산
# > L = [1, 2, 3, 4, 5]
# > arr = [1 2 3 4 5]
print(L * 2)     # 파이썬 리스트
print(arr * 2)   # 넘파이 배열

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]


In [ ]:
# --- (NOTE)
print(arr * arr) 

[ 1  4  9 16 25]


In [ ]:
# --- 만약 리스트로 위의 넘파이 배열과 같은 계산을 하려면...
# > arr = [1 2 3 4 5]
# > arr * 2 => [2 4 6 8 10]
# > L = [1, 2, 3, 4, 5]
alist = []
for i in L:
  alist.append(i * 2)
else:
  print(alist)

[2, 4, 6, 8, 10]


In [ ]:
# --- 리스트 축약으로 하면...
# > arr = [1 2 3 4 5]
# > arr * 2 => [2 4 6 8 10]
# > L = [1, 2, 3, 4, 5]
[(i * 2) for i in L]

[2, 4, 6, 8, 10]

### 2차원 곱하기 연산

In [ ]:
# --- 2차원 곱하기 연산
# > L2 = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
# > arr2 = [[1 2 3 4 5] [6 7 8 9 10]]
print(L2 * 2)     # 파이썬 리스트
print(arr2 * 2)   # 넘파이 배열

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
[[ 2  4  6  8 10]
 [12 14 16 18 20]]


In [ ]:
# --- 만약 리스트로 위의 넘파이 배열과 같은 계산을 하려면...
# > arr2 = [[1  2  3  4  5] [6  7  8  9 10]]
# > arr2 * 2 => [[2 4 6 8 10] [12 14 16 18 20]]
# > L2 = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
list2 = []
for row in L2:
  tmp = []
  for column in row:
    tmp.append(column * 2)
  else:
    list2.append(tmp)
else:
    print(list2)    

[[2, 4, 6, 8, 10], [12, 14, 16, 18, 20]]


In [ ]:
# --- 리스트 축약으로 하면...
# > arr2 = [[1  2  3  4  5] [6  7  8  9 10]]
# > arr2 * 2 => [[2 4 6 8 10] [12 14 16 18 20]]
# > L2 = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
[[column * 2 for column in row] for row in L2]

[[2, 4, 6, 8, 10], [12, 14, 16, 18, 20]]

# 배열 생성

## array() 함수

**array()** 함수로 다차원 배열을 생성하여 배열 안의 배열로 차원을 구분한다.   

[numpy.array](https://docs.scipy.org/doc/numpy/reference/generated/numpy.array.html?highlight=array#numpy.array)
- Create an array.
- numpy.**array**(*object, dtype=None, copy=True, order='K', subok=False, ndmin=0*)
    - ***object*** : *array_like*
        - An array, any object exposing the array interface, an object whose **\_\_array\_\_** method returns an array, or any (nested) sequence.

<!--
numpy.array(object, dtype=None, copy=True, order=’K’, subok=False, ndmin=0) 
- Create an array. 
- Returns — ndarray
    - An array object satisfying the specified requirements.
- Parameters
    - object — array_like 
        - An array, any object exposing the array interface, an object whose __array__ method returns an array, or any (nested) sequence. 
    - dtype — data-type, optional 
        - The desired data-type for the array. 
        - If not given, then the type will be determined as the minimum type required to hold the objects in the sequence. 
        - This argument can only be used to ‘upcast’ the array. 
            - For downcasting, use the .astype(t) method. 
    - copy — bool, optional 
        - If true (default), then the object is copied. 
        - Otherwise, a copy will only be made if __array__ returns a copy, if obj is a nested sequence, or if a copy is needed to satisfy any of the other requirements (dtype, order, etc.). 
    - order — {‘K’, ‘A’, ‘C’, ‘F’}, optional 
        - Specify the memory layout of the array. 
        - If object is not an array, the newly created array will be in C order (row major) unless ‘F’ is specified, in which case it will be in Fortran order (column major). 
        - If object is an array the following holds. on. The default order is ‘K’. 
    - subok — bool, optional
        - If True, then sub-classes will be passed-through, 
        - otherwise the returned array will be forced to be a base-class array (default). 
    - ndmin — int, optional 
        - Specifies the minimum number of dimensions that the resulting array should have. Ones will be pre-pended to the shape as needed to meet this requirement. 
-->

### 1차원 배열
- 일반적으로 리스트를 배열로 변환하여 반환한다.
    - 리스트 —> 배열

In [ ]:
# 1차원 배열을 만든다.
arr1 = numpy.array([1, 2, 3])  
print(arr1)
print(type(arr1))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
# (ok) 배열로 만들 전달인자(object)는 하나다.
numpy.array(1)

array(1)

In [ ]:
# (ok) 배열로 만들 전달인자는 하나다.
numpy.array(1, float)  # numpy.array(1, 'float')와 같다.

array(1.)

In [ ]:
# (ok) 배열로 만들 전달인자는 하나다.
numpy.array(1.0, 'int')  # numpy.array(1.0, int)와 같다.

array(1)

### 다차원 배열
- 리스트를 배열로 변환하여 반환한다.
    - 리스트 —> 배열 

In [ ]:
# 2차원 배열을 만든다.
arr2 = numpy.array([[1, 2, 3],   
                    [4, 5, 6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

## arange() 함수

[numpy.arange](https://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html#numpy.arange)
- Return evenly spaced values within a given interval.
- numpy.**arange**(*[start, ]stop, [step, ]dtype=None*)

In [ ]:
# 1차원 정수 배열을 만든다.
arr = numpy.arange(10)
print(arr)
print(type(arr))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [ ]:
# 1차원 실수 배열를 만든다.
numpy.arange(10, dtype='float64')  

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
# 1차원 실수 배열를 만든다.
numpy.arange(10, dtype=numpy.float64)  

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
# 1차원 실수 배열을 만든다.
numpy.arange(10.0)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
# 1차원 정수 배열을 만든다.
numpy.arange(3, 10)  

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 1차원 실수 배열을 만든다.
numpy.arange(3, 10, 2, dtype=numpy.float64)

array([3., 5., 7., 9.])

In [ ]:
# 1차원 정수 배열을 만든다.
numpy.arange(10, 3, -2)

array([10,  8,  6,  4])

In [ ]:
# 1차원 정수 배열을 만든다.
numpy.arange(3, 10, -2)

array([], dtype=int64)

## 내장함수

NumPy에 내장된 다양한 함수로도 배열을 만들 수 있다.

### zeros() 함수

[numpy.zeros](https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros.html?highlight=zeros#numpy.zeros)
- Return a new array of given shape and type, filled with zeros.
- numpy.**zeros**(*shape, dtype=float, order='C'*)
    - ***dtype*** : *data-type, optional*
        - Default is **numpy.float64**.
    - ***order*** : *{‘C’, ‘F’}, optional, default: C*
        - Whether to store multi-dimensional data in row-major (C-style) or column-major (Fortran-style) order in memory.

In [ ]:
# 모든 값이 실수 0.0인 2차원(3 x 2) 배열을 만든다.
numpy.zeros((3, 2)) 

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

### eye() 함수

[numpy.eye](https://docs.scipy.org/doc/numpy/reference/generated/numpy.eye.html?highlight=eye#numpy.eye)
- Return a 2-D array with ones on the diagonal and zeros elsewhere.
- numpy.**eye**(*N, M=None, k=0, dtype=<class 'float'>, order='C'*)
    - ***N*** : *int*
        - Number of rows in the output.
    - ***M*** : *int, optional*
        - Number of columns in the output. If **None**, defaults to N.
    - ***k*** : *int, optional*
        - Index of the diagonal: **0** (the default) refers to the main diagonal, a positive value refers to an upper diagonal, and a negative value to a lower diagonal.
    - Returns: *ndarray of shape (N,M)*
        - An array where all elements are equal to zero, except for the *k*-th diagonal, whose values are equal to one.

In [ ]:
# 단위행렬 2차원(5 x 5) 배열을 만든다.
numpy.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# 단위행렬 2차원(5 x 2) 배열을 만든다.
numpy.eye(5, 2)

array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
# 단위행렬 2차원(5 x 5) 배열 주사선의 
# 상단 1 위의 사선을 1.0으로 채운 배열을 만든다.
numpy.eye(5, k=1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [ ]:
# 단위행렬 2차원(5 x 5) 배열 주사선의 
# 하단 2 아래의 사선을 1.0으로 채운 배열을 만든다.
numpy.eye(5, k=-2)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

### diag() 함수

[numpy.diag](https://docs.scipy.org/doc/numpy/reference/generated/numpy.diag.html?highlight=diag#numpy.diag)
- Extract a diagonal or construct a diagonal array.
- numpy.**diag**(*v, k=0*)
    - ***v*** : *array_like*
        - **v**가 2차원일 때와 1차원일 때 작동 방식이 다르다.
            - If ***v*** is a 2-D array, return a copy of its *k*-th diagonal. ***v***가 2차원 배열이면, 그 배열의 사선을 추출해서 1차원 배열을 만든다.
            - If ***v*** is a 1-D array, return a 2-D array with ***v*** on the *k*-th diagonal. ***v***가 1차원 배열이면, 그 배열의 값을 사선으로 가지는 2차원 배열을 반환한다.
    - ***k*** : *int, optional*
        - Diagonal in question. The default is **0**. Use *k > 0* for diagonals above the main diagonal, and *k < 0* for diagonals below the main diagonal.

In [ ]:
# 2차원(3 x 4) 배열
arr = numpy.array([[0, 1, 2, 3], 
                   [4, 5, 6, 7], 
                   [8, 9, 10, 11]])
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# 첫 번째 전달인자가 2차원(3 x 4) 배열이면, 
# 그 배열의 사선을 추출해서 1차원 배열을 만든다.
numpy.diag(arr)   

array([ 0,  5, 10])

In [ ]:
# 2차원(3 x 4) 배열 주사선의 
# 상단 1 위의 사선을 추출해서 1차원 배열을 만든다.
numpy.diag(arr, k=1)  

array([ 1,  6, 11])

In [ ]:
# 2차원(3 x 4) 배열 주사선의 
# 하단 2 아래의 사선을 추출해서 1차원 배열을 만든다.
numpy.diag(arr, k=-2)

array([8])

In [ ]:
# 첫 번째 전달인자가 1차원 배열이면, 
# 그 배열의 값을 사선으로 가지는 2차원 배열을 반환한다.
numpy.diag([1, 5, 10])

array([[ 1,  0,  0],
       [ 0,  5,  0],
       [ 0,  0, 10]])

In [ ]:
# 첫 번째 전달인자가 1차원 배열이고 k 값이 주어지면, 
# 그 배열의 값을 k만큼 이동한 사선으로 가지는 2차원 배열을 만든다.
numpy.diag([1, 5, 10], k=-2)

array([[ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 1,  0,  0,  0,  0],
       [ 0,  5,  0,  0,  0],
       [ 0,  0, 10,  0,  0]])

### random.random() 함수

[numpy.random.Generator.random](https://docs.scipy.org/doc/numpy/reference/random/generated/numpy.random.Generator.random.html#numpy.random.Generator.random)
- **Uniform([0, 1))** 을 따르는 난수를 생성한다.
- Return random floats in the half-open interval [0.0, 1.0).
- Results are from the “continuous uniform” distribution over the stated interval.
- To sample $ Unif[a, b), b > a $ multiply the output of random by *(b-a)* and add *a*:

```
(b - a) * random() + a
```

- Generator.**random**(*size=None, dtype='d', out=None*)
    - ***size*** : *int or tuple of ints, optional*
        - Output shape. If the given shape is, e.g., **(m, n, k)**, then m * n * k samples are drawn. 
        - Default is **None**, in which case **a single value** is returned.
    - ***dtype*** : *{str, dtype}, optional*
        - Desired dtype of the result, either ‘d’ (or ‘float64’) or ‘f’ (or ‘float32’). All dtypes are determined by their name. 
        - The default value is ‘d’.
    - ***out*** : *ndarray, optional*
        - Alternative output array in which to place the result. If size is not **None**, it must have the same shape as the provided size and must match the type of the output values.

In [ ]:
# 임의의 실수(0 이상 1 이하)를 만든다.
numpy.random.random()

0.158669862621163

In [ ]:
# 임의의 실수(0 이상 1 이하)로 채워진 1차원(5,) 배열을 만든다.
numpy.random.random(5)

array([0.51007175, 0.95131489, 0.44683025, 0.14221   , 0.62536888])

In [ ]:
# 임의의 실수(0 이상 1 이하)로 채워진 2차원(1 x 5) 배열을 만든다.
numpy.random.random((1, 5))

array([[0.01113246, 0.59185488, 0.68591321, 0.47793059, 0.37867388]])

In [ ]:
# 임의의 실수(0 이상 1 이하)로 채워진 2차원(2 x 5) 배열을 만든다.
numpy.random.random((2, 5))

array([[0.55054822, 0.64118906, 0.16147678, 0.00659165, 0.0820999 ],
       [0.4486739 , 0.94477232, 0.85518623, 0.64791878, 0.56812962]])

### random.randint() 함수

[numpy.random.mtrand.RandomState.randint](https://docs.scipy.org/doc/numpy/reference/random/generated/numpy.random.mtrand.RandomState.randint.html#numpy.random.mtrand.RandomState.randint)
- Return random integers from ***low*** (inclusive) to ***high*** (exclusive).
- Return random integers from the “discrete uniform” distribution of the specified dtype in the “half-open” interval **[low, high)**. If ***high*** is **None** (the default), then results are from **[0, low)**.
- RandomState.**randint**(*low, high=None, size=None, dtype='l'*)
    - ***low*** : *int or array-like of ints*
        - Lowest (signed) integers to be drawn from the distribution (unless **high=None**, in which case this parameter is one above the highest such integer).
    - ***high*** : *int or array-like of ints, optional*
        - If provided, one above the largest (signed) integer to be drawn from the distribution (see above for behavior if **high=None**). If array-like, must contain integer values
    - ***size*** : *int or tuple of ints, optional*
        - Output shape. If the given shape is, e.g., **(m, n, k)**, then m * n * k samples are drawn. 
        - Default is **None**, in which case a single value is returned.
    - ***dtype*** : *dtype, optional*
        - Desired dtype of the result. All dtypes are determined by their name, i.e., ‘int64’, ‘int’, etc, so byteorder is not available and a specific precision may have different C types depending on the platform. 
        - The default value is ‘np.int’.

In [ ]:
# 0~4 사이의 임의의 정수로 채워진 1차원(10,) 배열을 만든다.
numpy.random.randint(5, size=10)

array([2, 2, 4, 1, 4, 2, 4, 3, 4, 3])

In [ ]:
# 0~4 사이의 임의의 정수로 채워진 2차원(2 x 5) 배열을 만든다.
numpy.random.randint(5, size=(2, 5))

array([[2, 1, 1, 0, 3],
       [3, 3, 3, 2, 1]])

In [ ]:
# 1 이상 (3 미만, 5 미만, 10 미만)의 
# 임의의 정수로 채워진 1차원(3) 배열을 만든다.
numpy.random.randint(1, [3, 5, 10])

array([1, 4, 9])

In [ ]:
# (1 이상, 3 이상, 5 이상, 7 이상, 9 이상) 10 미만의 
# 임의의 정수로 채워진 1차원(3) 배열을 만든다.
numpy.random.randint([1, 3, 5, 7, 9], 10)

array([1, 4, 8, 9, 9])

In [ ]:
# (1, 3, 5, 7 이상) x (첫 번째 행은 10 미만, 두 번째 행은 20 미만)의 
# 임의의 정수(uint)로 채워진 2차원(2 x 4) 배열을 만든다.
numpy.random.randint([1, 3, 5, 7], [[10], [20]], dtype=numpy.uint)

array([[ 2,  3,  8,  9],
       [ 7, 18,  9, 10]], dtype=uint64)

### Lab: 랜덤 벡터 생성과 정렬

- - -

- 길이 **10**인 랜덤 벡터(**1**차원 배열)을 생성하고 이를 정렬한다.

- 오름차순과 내림차순으로 한 번씩 정렬해 본다.

- - -

In [ ]:
import numpy

# 길이 10인 랜덤 벡터(1차원 배열)을 생성
arr = numpy.random.random(10)
arr

array([0.57325185, 0.69779706, 0.70366113, 0.01521645, 0.64375947,
       0.92207272, 0.02126062, 0.12492399, 0.3617444 , 0.2533235 ])

In [ ]:
# 오름차순으로 정렬한다.
arr.sort()  
arr 

array([0.01521645, 0.02126062, 0.12492399, 0.2533235 , 0.3617444 ,
       0.57325185, 0.64375947, 0.69779706, 0.70366113, 0.92207272])

In [ ]:
# 내림차순으로 정렬한다.
arr[::-1].sort()  
arr 

array([0.92207272, 0.70366113, 0.69779706, 0.64375947, 0.57325185,
       0.3617444 , 0.2533235 , 0.12492399, 0.02126062, 0.01521645])

# 배열 자료형

[numpy.ndarray.**dtype**](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.dtype.html?highlight=dtype#numpy.ndarray.dtype)

- 배열의 자료형을 알려준다.

In [ ]:
arr1 = numpy.array([[1, 2, 3], [4, 5, 6]])
arr1.dtype, arr1.dtype.name

(dtype('int64'), 'int64')

In [ ]:
arr2 = numpy.array([1.0])
arr2.dtype

dtype('float64')

In [ ]:
arr3 = numpy.array([1, 2], dtype = numpy.float64)
arr3.dtype.name

'float64'

## 형변환 메소드

[numpy.ndarray.astype](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.astype.html?highlight=astype#numpy.ndarray.astype)

- Copy of the array, cast to a specified type.
- ndarray.**astype**(*dtype, order='K', casting='unsafe', subok=True, copy=True*)
    - ***dtype*** : *str or dtype*
        - Typecode or data-type to which the array is cast.
    - Returns:
        - ***arr_t*** : *ndarray*
            - Unless ***copy*** is **False** and the other conditions for returning the input array are satisfied, ***arr_t*** is a new array of the same shape as the input array, with dtype, order given by dtype, order.

In [ ]:
arr = numpy.arange(1, 13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
# 2차원(3 x 4) 배열로 변형한다.
arr.shape = (3, 4)  
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# 8-bit unsigned integer로 형변환한 numpy array를 생성한다.
arr.astype('uint8')  

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]], dtype=uint8)

In [ ]:
# 정수를 문자열로 형변환한 numpy array를 생성한다.
arr.astype('str')

array([['1', '2', '3', '4'],
       ['5', '6', '7', '8'],
       ['9', '10', '11', '12']], dtype='<U21')

In [ ]:
# 문자열을 실수로 형변환한 numpy array를 생성한다.
numpy.array(['3.14', '-1.234', '0.9']).astype('float')

array([ 3.14 , -1.234,  0.9  ])

**참고**
- [NumPy 자료형](https://docs.scipy.org/doc/numpy/user/basics.types.html)

|Data Types|Description
:-|:-
**bool_**|Boolean (True or False) stored as a byte
**uint8**|Unsigned integer (0 to 255)
**uint16**|Unsigned integer (0 to 65535)
**uint32**|Unsigned integer (0 to 4294967295)
**uint64**|Unsigned integer (0 to 18446744073709551615)
**int_**|Default integer type (same as C long; normally either int64 or int32)
**intc**|Identical to C int (normally int32 or int64)
**intp**|Integer used for indexing (same as C ssize_t; normally either int32 or int64)
**int8**|Byte (-128 to 127)
**int16**|Integer (-32768 to 32767)
**int32**|Integer (-2147483648 to 2147483647)
**int64**|Integer (-9223372036854775808 to 9223372036854775807)
**float_**|Shorthand for float64
**float16**|Half precision float: sign bit, 5 bits exponent, 10 bits mantissa
**float32**|Single precision float: sign bit, 8 bits exponent, 23 bits mantissa
**float64**|Double precision float: sign bit, 11 bits exponent, 52 bits mantissa
**complex_**|Shorthand for complex128
**complex64**|Complex number, represented by two 32-bit floats (real and imaginary components)
**complex128**|Complex number, represented by two 64-bit floats (real and imaginary components)

<div align='right'><span style='font-size: smaller;'>[출처: https://www.tutorialspoint.com/numpy/numpy_data_types.htm]</span></div>

# 배열의 차원

## 차원(rank) : ndim

[numpy.ndarray.**ndim**](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.ndim.html?highlight=ndarray%20ndim#numpy.ndarray.ndim)
- Number of array dimensions.
- 배열이 몇 차원인지 알려준다.
- 배열의 차원을 **rank**라 부른다.

In [ ]:
# 1차원(3) 배열을 반환한다. rank = 1
arr1 = numpy.array([1, 2, 3])  
arr1.ndim

1

In [ ]:
# 2차원(2 x 3)배열을 반환한다. rank = 2
arr2 = numpy.array([[1, 2, 3], 
                    [4, 5, 6]])  
arr2.ndim

2

In [ ]:
# 3차원(3 x 2 x 4) 배열을 반환한다. rank = 3
arr3 = numpy.array([[[1, 2, 3, 4], 
                     [5, 6, 7, 8]],
                    
                    [[9, 10, 11, 12], 
                     [13, 14, 15, 16]],
                   
                    [[17, 18, 19, 20],
                     [21, 22, 23, 24]]])  
arr3.ndim

3

## 차원 형태 : shape

[numpy.ndarray.**shape**](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.shape.html?highlight=shape#numpy.ndarray.shape)
- Tuple of array dimensions.
- 차원 형태를 튜플 자료형으로 알려준다.

In [ ]:
# 1차원(3) 배열을 반환한다.
arr1 = numpy.array([1, 2, 3])  
arr1.shape

(3,)

In [ ]:
# 2차원(2 x 3)배열을 반환한다.
arr2 = numpy.array([[1, 2, 3], 
                    [4, 5, 6]])  
arr2.shape

(2, 3)

In [ ]:
# 3차원(3 x 2 x 4) 배열을 반환한다.
arr3 = numpy.array([[[1, 2, 3, 4], 
                     [5, 6, 7, 8]],
                    
                    [[9, 10, 11, 12], 
                     [13, 14, 15, 16]],
                   
                    [[17, 18, 19, 20],
                     [21, 22, 23, 24]]])  
arr3.shape

(3, 2, 4)

## 차원 변경 : reshape()

[**numpy.ndarray.reshape**](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.reshape.html#numpy.ndarray.reshape)
- **reshape()** 함수로 차원을 변경할 수 있다.
- Gives a new shape to an array without changing its data.
- ndarray.**reshape**(*shape, order='C'*)
    - Refer to **numpy.reshape** for full documentation.

In [ ]:
# 1차원 배열을 생성한다.
arr = numpy.arange(15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
# 1차원 배열로 2차원 배열(3 x 5)을 생성한다.
arr.reshape(3, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
# 1차원 배열 arr를 2차원 배열(5 x 3)로 바꾼다.
arr = arr.reshape(5, 3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
# 1차원 배열을 3차원 배열(3 x 2 x 4)로 바꾼다.
arr = numpy.arange(1, 25).reshape(3, 2, 4)
arr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]])

## Lab: 벡터를 행렬로 변환하기

- - -

길이 **9**의 벡터(**1**차원 배열)를 생성하고 이를 **3** x **3** 크기의 행렬로 변환한다.

- - -

**힌트**
- NumPy의 **arange()** 함수를 이용해 **0**부터 **8**까지의 정수를 담은 1차원 배열을 생성한다.
- 이를 **reshape()** 함수로 2차원 배열로 변환하면 된다.

In [ ]:
import numpy

# 길이 9의 벡터(1차원 배열)를 생성한다.
arr = numpy.arange(9)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
# 길이 9의 벡터(1차원 배열)를 3 x 3 크기의 행렬로 변환한다.
arr = arr.reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Lab: 대각행렬(diagonal matrix)

- - -

길이 **9**의 벡터(**1**차원 배열)를 생성한 후 생성한 행렬을 대각행렬로 변환한다.

1. 우선 행렬의 주대각 원소(대각선상에 있는 원소)만 **1**차원 배열로 출력한다.
1. **3** x **3** 대각행렬(정사각행렬의 주대각 성분 이외의 모든 성분이 **0**인 행렬)로 변환한다.

- - -

In [ ]:
import numpy

# 길이 9의 벡터(1차원 배열)를 생성한 후 2차원 3 x 3 크기의 행렬로 변환한다.
arr = numpy.arange(9).reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
# 행렬의 주대각 원소(대각선상에 있는 원소)만 1차원 배열로 출력한다.
diag = numpy.diag(arr)
diag

array([0, 4, 8])

In [ ]:
# 3 x 3 대각행렬(정사각행렬의 주대각 성분 이외의 모든 성분이 0인 행렬)로 변환한다.
diag_mat = numpy.diag(numpy.diag(arr))
diag_mat

array([[0, 0, 0],
       [0, 4, 0],
       [0, 0, 8]])

# 기본 연산

요소별 합/차/곱/나눗셈/제곱근/지수/불린

**NumPy** 기본 연산의 특징
- NumPy의 기본 연산자는 배열이 담고 있는 개별 값별로 계산을 한다.

In [ ]:
arr1 = numpy.array([[1, 2], [3, 4]], dtype = numpy.int_)
arr2 = numpy.array([[5, 6], [7, 8]], dtype = numpy.int_)

In [ ]:
arr1

array([[1, 2],
       [3, 4]])

In [ ]:
arr2

array([[5, 6],
       [7, 8]])

In [ ]:
# > arr1 = [[1 2] [3 4]]
# > arr2 = [[5 6] [7 8]] 
# arr1과 arr2 더하기
arr1 + arr2  

array([[ 6,  8],
       [10, 12]])

In [ ]:
# > arr1 = [[1 2] [3 4]]
# > arr2 = [[5 6] [7 8]] 
# arr1에서 arr2 빼기
arr1 - arr2  

array([[-4, -4],
       [-4, -4]])

In [ ]:
# > arr1 = [[1 2] [3 4]]
# > arr2 = [[5 6] [7 8]] 
# arr1과 arr2 곱하기 : 행렬의 곱연산이 아니다.
arr1 * arr2  

array([[ 5, 12],
       [21, 32]])

In [ ]:
# > arr1 = [[1 2] [3 4]]
# > arr2 = [[5 6] [7 8]] 
# arr1를 arr2로 나누기
arr1 / arr2  

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [ ]:
# > arr1 = [[1 2] [3 4]]
# > arr2 = [[5 6] [7 8]] 
# arr1를 arr2로 나눈 몫 구하기
arr2 // arr1  

array([[5, 3],
       [2, 2]])

In [ ]:
# > arr1 = [[1 2] [3 4]]
# > arr2 = [[5 6] [7 8]] 
# arr1를 arr2로 나눈 나머지 구하기
arr2 % arr1  

array([[0, 0],
       [1, 0]])

In [ ]:
# > arr1 = [[1 2] [3 4]]
# arr1의 제곱근 구하기
numpy.sqrt(arr1)  

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [ ]:
# > arr1 = [[1 2] [3 4]]
# 지수 : arr1의 3 승 
arr1 ** 3  

array([[ 1,  8],
       [27, 64]])

In [ ]:
# > arr1 = [[1 2] [3 4]]
# > arr2 = [[5 6] [7 8]] 
# 지수 : arr2의 arr1 승
arr2 ** arr1  

array([[   5,   36],
       [ 343, 4096]])

In [ ]:
# > arr2 = [[5 6] [7 8]] 
# 불린 : arr2의 값 중 7보다 작은 값의 불린 배열
arr2 < 7  

array([[ True,  True],
       [False, False]])

# 행렬 연산

## 행렬 합 : **numpy.sum()**

[numpy.sum](https://docs.scipy.org/doc/numpy/reference/generated/numpy.sum.html?highlight=sum#numpy.sum)
- Sum of array elements over a given axis.
- numpy.**sum**(*a, axis=None, dtype=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>*)
    - ***a*** : *array_like*
        - Elements to sum.
    - ***axis*** : *None or int or tuple of ints*, optional
        - Axis or axes along which a sum is performed. 
        - The default, **axis=None**, will **sum all of the elements** of the input array. 
        - If axis is **negative** it counts from the last to the first axis.
        - If axis is a tuple of ints, a sum is performed on all of the axes specified in the tuple instead of a single axis or all the axes as before.
    - Returns:
        - sum_along_axis : *ndarray*
            - An array with the same shape as *a*, with the specified axis removed. If *a* is a **0-d array**, or if ***axis*** is **None**, a **scalar** is returned. If an ***output*** array is specified, a reference to out is returned.

[numpy.ndarray.sum](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.sum.html?highlight=sum#numpy.ndarray.sum)
- Return the sum of the array elements over the given axis.
- ndarray.**sum**(*axis=None, dtype=None, out=None, keepdims=False, initial=0, where=True*)
    - Refer to [numpy.sum](https://docs.scipy.org/doc/numpy/reference/generated/numpy.sum.html?highlight=sum#numpy.sum) for full documentation.    

[numpy.matrix.sum](https://docs.scipy.org/doc/numpy/reference/generated/numpy.matrix.sum.html?highlight=sum#numpy.matrix.sum)
- Returns the sum of the matrix elements, along the given axis.
- matrix.**sum**(*self, axis=None, dtype=None, out=None*)
    - Refer to [numpy.sum](https://docs.scipy.org/doc/numpy/reference/generated/numpy.sum.html?highlight=sum#numpy.sum) for full documentation.    

In [ ]:
arr = numpy.array([[1, 2], [3, 4], [5, 6]], 
                  dtype=numpy.float64)
arr

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [ ]:
# > arr = [[1. 2.]
#          [3. 4.]
#          [5. 6.]]
# arr 모든 값의 합을 구한다.
numpy.sum(arr)

21.0

In [ ]:
# > arr = [[1. 2.]
#          [3. 4.]
#          [5. 6.]]
# arr의 행 축을 기준으로 각 행의 동일 인덱스에 있는 값의 합을 구한다.  (sum of each column)
numpy.sum(arr, axis=0)  

array([ 9., 12.])

In [ ]:
# > arr = [[1. 2.]
#          [3. 4.]
#          [5. 6.]]
# arr의 열 축을 기준으로 각 행의 합을 구한다. (sum of each row)
numpy.sum(arr, axis=1)  

array([ 3.,  7., 11.])

## 내적 및 행렬 곱 : **numpy.dot()**

**array()** 함수로 다차원 배열을 생성하여 배열 안의 배열로 차원을 구분한다.   

[numpy.dot](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html?highlight=dot)  
Dot product of two arrays. Specifically,
- If **both** *a* and *b* are **1-D arrays**, it is **inner product** of vectors (without complex conjugation).
- If **both** *a* and *b* are **2-D arrays**, it is **matrix multiplication**, but using [matmul](https://docs.scipy.org/doc/numpy/reference/generated/numpy.matmul.html#numpy.matmul) or **a @ b** is preferred.
- If **either** *a* or *b* is **0-D** (scalar), it is equivalent to [multiply](https://docs.scipy.org/doc/numpy/reference/generated/numpy.multiply.html#numpy.multiply) and using **numpy.multiply(a, b)** or **a * b** is preferred.
- If *a* is an **N-D array** and *b* is a **1-D array**, it is a sum product over the last axis of *a* and *b*.
- If *a* is an **N-D array** and *b* is an **M-D array** (where M>=2), it is a sum product over the last axis of *a* and the second-to-last axis of *b*:

```
dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])
```


- numpy.**dot**(*a, b, out=None*)
    - ***a*** : *array_like*
        - First argument.
    - ***b*** : *array_like*
        - Second argument.
    - ***out*** : *ndarray*, optional
        - Output argument. This must have the exact kind that would be returned if it was not used. In particular, it must have the right type, must be C-contiguous, and its dtype must be the dtype that would be returned for **dot(a, b)**. This is a performance feature. Therefore, if these conditions are not met, an exception is raised, instead of attempting to be flexible.
    - Returns:
        - output : *ndarray*
            - Returns the dot product of *a* and *b*. If *a* and *b* are *both* **scalars** or *both* **1-D arrays** then a **scalar**( is returned; *otherwise* an **array** is returned. If ***out*** is given, then it is returned.


[numpy.ndarray.dot](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.dot.html?highlight=dot#numpy.ndarray.dot)
- Dot product of two arrays.
- ndarray.**dot**(*b, out=None*)
    - Refer to 
[numpy.dot](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html?highlight=dot) for full documentation.


[numpy.matrix.dot](https://docs.scipy.org/doc/numpy/reference/generated/numpy.matrix.dot.html?highlight=dot#numpy.matrix.dot)
- Dot product of two arrays.
- matrix.**dot**(*b, out=None*)
    - Refer to 
[numpy.dot](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html?highlight=dot) for full documentation.

In [ ]:
# --- 둘 다 1차원 벡터면, 벡터의 내적을 구한다.
v1 = numpy.array([1, 2])
v2 = numpy.array([3, 4])

# v1과 v2의 내적을 구한다.
numpy.dot(v1, v2)

11

In [ ]:
# -- 둘 다 2차원 행렬이면, 행렬의 곱 연산을 구한다.
arr1 = numpy.array([[1, 2], [3, 4]], dtype=numpy.float_)
arr2 = numpy.array([[5, 6], [7, 8]], dtype=numpy.float_)

# arr1과 arr2의 행렬 곱을 구한다.
numpy.dot(arr1, arr2)

array([[19., 22.],
       [43., 50.]])

In [ ]:
# > arr1 = [[1. 2.] 
#           [3. 4.]]
# > arr2 = [[5. 6.] 
#           [7. 8.]]
# 행렬 곱 연산은 dot()보다 matmul()이나 @가 좋다.
# matmul()을 사용하여 arr1과 arr2의 행렬 곱을 구한다.
numpy.matmul(arr1, arr2)

array([[19., 22.],
       [43., 50.]])

In [ ]:
# > arr1 = [[1. 2.] 
#           [3. 4.]]
# > arr2 = [[5. 6.] 
#           [7. 8.]]
# 행렬 곱 연산은 dot()보다 matmul()이나 @가 좋다.
# @를 사용하여 arr1과 arr2의 행렬 곱을 구한다.
arr1 @ arr2

array([[19., 22.],
       [43., 50.]])

In [ ]:
# > arr1 = [[1. 2.] 
#           [3. 4.]]
# 둘 중 하나가 스카라면, 요소별 곱 연산을 구한다.
# (방법 1) arr1에 5를 곱한다.
numpy.dot(arr1, 5)

array([[ 5., 10.],
       [15., 20.]])

In [ ]:
# > arr1 = [[1. 2.] 
#           [3. 4.]]
# 둘 중 하나가 스카라면, 요소별 곱 연산을 구한다.
# (방법 2) arr1에 5를 곱한다.
arr1.dot(5)

array([[ 5., 10.],
       [15., 20.]])

### 곱하기 연산 비교

In [ ]:
arr1 = numpy.array([[-1, 0], [1, 2]])
arr2 = numpy.array([[3, 4], [-5, 1]])

In [ ]:
arr1

array([[-1,  0],
       [ 1,  2]])

In [ ]:
arr2

array([[ 3,  4],
       [-5,  1]])

In [ ]:
# > arr1 = [[-1  0]
#           [ 1  2]]
# > arr2 = [[ 3  4]
#           [-5  1]]
# arr1와 arr2를 요소별 곱하기
arr1 * arr2  

array([[ 5., 12.],
       [21., 32.]])

In [ ]:
# > arr1 = [[-1  0]
#           [ 1  2]]
# > arr2 = [[ 3  4]
#           [-5  1]]
# arr2와 arr1을 요소별 곱하기
arr2 * arr1

array([[ 5., 12.],
       [21., 32.]])

In [ ]:
# > arr1 = [[-1  0]
#           [ 1  2]]
# > arr2 = [[ 3  4]
#           [-5  1]]
# arr1과 arr2를 행렬 곱하기
numpy.dot(arr1, arr2)

array([[19., 22.],
       [43., 50.]])

In [ ]:
# > arr1 = [[-1  0]
#           [ 1  2]]
# > arr2 = [[ 3  4]
#           [-5  1]]
# arr2와 arr1을 행렬 곱하기
numpy.dot(arr2, arr1)

array([[23., 34.],
       [31., 46.]])

In [ ]:
# > arr1 = [[-1  0]
#           [ 1  2]]
# > arr2 = [[ 3  4]
#           [-5  1]]
# arr1에 arr2를 행렬 곱하기
arr1.dot(arr2)

array([[19., 22.],
       [43., 50.]])

In [ ]:
# > arr1 = [[-1  0]
#           [ 1  2]]
# > arr2 = [[ 3  4]
#           [-5  1]]
# arr2에 arr1을 행렬 곱하기
arr2.dot(arr1)

array([[23., 34.],
       [31., 46.]])

In [ ]:
# > arr1 = [[-1  0]
#           [ 1  2]]
# > arr2 = [[ 3  4]
#           [-5  1]]
# arr1와 arr2를 @로 행렬 곱하기(since Python 3.5)
arr1 @ arr2

array([[19., 22.],
       [43., 50.]])

In [ ]:
# > arr1 = [[-1  0]
#           [ 1  2]]
# > arr2 = [[ 3  4]
#           [-5  1]]
# arr2와 arr1을 @로 행렬 곱하기(since Python 3.5)
arr2 @ arr1

array([[23., 34.],
       [31., 46.]])

## 행렬의 전치 연산

[numpy.ndarray.transpose](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.transpose.html?highlight=.t#numpy.ndarray.transpose)
- Returns a view of the array with axes transposed.
- For a **1-D array** this has no effect, as a transposed vector is simply the same vector. 
    - To convert a 1-D array into a 2D column vector, an additional dimension must be added. **np.atleast2d(a).T** achieves this, as does **a[:, np.newaxis]**. 
- For a **2-D array**, this is a standard matrix transpose. 
- For an **n-D array**, if axes are given, their order indicates how the axes are permuted (see Examples). 
- If axes are not provided and `a.shape = (i[0], i[1], ... i[n-2], i[n-1])`, then `a.transpose().shape = (i[n-1], i[n-2], ... i[1], i[0])`.
- ndarray.**transpose**(<i>*axes<\i>)
    - ***axes*** : *None, tuple of ints, or n ints*
        - **None** or no argument: reverses the order of the axes.
        - tuple of ints: *i* in the *j*-th place in the tuple means *a*’s *i*-th axis becomes **a.transpose()’s *j*-th** axis.
        - *n* ints: same as an *n*-tuple of the same ints (this form is intended simply as a “convenience” alternative to the tuple form)
    - Returns:
        - out : *ndarray*
            - View of *a*, with axes suitably permuted.

[numpy.ndarray.T](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.T.html?highlight=.t#numpy.ndarray.T)
- Attribute
- The transposed array.
- ndarray.**T**
    - see also [transpose](https://docs.scipy.org/doc/numpy/reference/generated/numpy.transpose.html#numpy.transpose)
    
[numpy.matrix.T](https://docs.scipy.org/doc/numpy/reference/generated/numpy.matrix.T.html?highlight=.t#numpy.matrix.T)    
- Attribute
- Returns the transpose of the matrix.
- Does not conjugate! For the complex conjugate transpose, use **.H**.

In [ ]:
arr = numpy.array([[1, 2], [3, 4], [5, 6]], 
                  dtype=numpy.float_)
arr

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [ ]:
# > arr = [[1. 2.]
#          [3. 4.]
#          [5. 6.]]
# arr의 행과 열을 바꾼다.
arr.T 

array([[1., 3., 5.],
       [2., 4., 6.]])

# 넘파이 배열 함수

**sum()**, **mean()**, **max()**, **min()**, **std()**, **var()**

[numpy.sort](https://docs.scipy.org/doc/numpy/reference/generated/numpy.sort.html#numpy.sort)
- Return a sorted copy of an array.
- numpy.**sort**(<i>\*, axis=-1, kind=None, order=None</i>)
    - ***a*** : *array_like*
        - Array to be sorted.
    - ***axis*** : *int or None, optional*
        - Axis along which to sort. 
        - If **None**, the array is flattened before sorting. 
        - The default is -1, which sorts along the last axis.
    - ***kind*** : *{‘quicksort’, ‘mergesort’, ‘heapsort’, ‘stable’}, optional*
        - Sorting algorithm. The default is ‘quicksort’. Note that both ‘stable’ and ‘mergesort’ use timsort or radix sort under the covers and, in general, the actual implementation will vary with data type. The ‘mergesort’ option is retained for backwards compatibility.
    - ***order*** : *str or list of str, optional*
        - When ***a*** is an array with fields defined, this argument specifies which fields to compare first, second, etc. A single field can be specified as a string, and not all fields need be specified, but unspecified fields will still be used, in the order in which they come up in the dtype, to break ties.

In [ ]:
numpy.random.seed(7)
arr1 = numpy.random.random((2, 3))
arr1

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587]])

In [ ]:
# arr1의 합을 구한다.
arr1.sum()  # numpy.sum(arr1)와 같다.

3.534586873292943

In [ ]:
# arr1의 평균을 구한다.
arr1.mean()  # numpy.mean(arr1)와 같다.

0.5890978122154905

In [ ]:
# arr1의 최댓값을 조회한다.
arr1.max()  # numpy.max(arr1)와 같다.

0.9779895119966027

In [ ]:
# arr1의 최솟값을 조회한다.
arr1.min()  # numpy.min(arr1)와 같다.

0.07630828937395717

In [ ]:
# arr1의 표준편차를 구한다.
arr1.std()  # numpy.std(arr1)와 같다.

0.2869159833891532

In [ ]:
# arr1의 분산을 구한다.
arr1.var()  # numpy.var(arr1)와 같다.

0.08232078152416482

In [ ]:
# arr1을 오름차순으로 정렬한다.
arr1.sort()  # arr1 = numpy.sort(arr1)와 같다.
arr1

array([[0.07630829, 0.43840923, 0.77991879],
       [0.53849587, 0.72346518, 0.97798951]])

In [ ]:
# 내림차순으로 정렬한다.
arr1[::-1, ::-1].sort()
arr1

array([[0.77991879, 0.43840923, 0.07630829],
       [0.97798951, 0.72346518, 0.53849587]])

In [ ]:
arr2 = numpy.arange(6).reshape(2, 3)
arr2

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
# > arr2 = [[0, 1, 2], 
#           [3, 4, 5]]
# arr2의 모든 값의 합, 
# 행 축을 기준으로 각 행의 동일 인덱스에 있는 값의 합, 
# 열 축을 기준으로 각 행의 합을 각각 구한다.
arr2.sum(), arr2.sum(axis=0), arr2.sum(axis=1)

(21, array([ 9, 12]), array([ 3,  7, 11]))

In [ ]:
# > arr2 = [[0, 1, 2], 
#           [3, 4, 5]]
# arr2의 모든 값의 평균, 
# 행 축을 기준으로 각 행의 동일 인덱스에 있는 값의 평균, 
# 열 축을 기준으로 각 행의 평균을 각각 구한다.
arr2.mean(), arr2.mean(axis=0), arr2.mean(axis=1)

(3.5, array([3., 4.]), array([1.5, 3.5, 5.5]))

In [ ]:
# > arr2 = [[0, 1, 2], 
#           [3, 4, 5]]
# arr2의 모든 값의 최댓값, 
# 행 축을 기준으로 각 행의 동일 인덱스에 있는 값의 최댓값, 
# 열 축을 기준으로 각 행의 최댓값을 각각 구한다.
arr2.max(), arr2.max(axis=0), arr2.max(axis=1)

(6, array([5, 6]), array([2, 4, 6]))

In [ ]:
# > arr2 = [[0, 1, 2], 
#           [3, 4, 5]]
# arr2의 모든 값의 최솟값, 
# 행 축을 기준으로 각 행의 동일 인덱스에 있는 값의 최솟값, 
# 열 축을 기준으로 각 행의 최솟값을 각각 구한다.
arr2.min(), arr2.min(axis=0), arr2.min(axis=1)

(1, array([1, 2]), array([1, 3, 5]))

In [ ]:
# > arr2 = [[0, 1, 2], 
#           [3, 4, 5]]
# arr2의 모든 값의 표준편차, 
# 행 축을 기준으로 각 행의 동일 인덱스에 있는 값의 표준편차, 
# 열 축을 기준으로 각 행의 표준편차를 각각 구한다.
arr2.std(), arr2.std(axis=0), arr2.std(axis=1)

(1.707825127659933, array([1.63299316, 1.63299316]), array([0.5, 0.5, 0.5]))

In [ ]:
# > arr2 = [[0, 1, 2], 
#           [3, 4, 5]]
# arr2의 모든 값의 분산, 
# 행 축을 기준으로 각 행의 동일 인덱스에 있는 값의 분산, 
# 열 축을 기준으로 각 행의 분산을 각각 구한다.
arr2.var(), arr2.var(axis=0), arr2.var(axis=1)

(2.9166666666666665,
 array([2.66666667, 2.66666667]),
 array([0.25, 0.25, 0.25]))

## Lab: 행렬 정규화(normalization)

- - -

정수로 이루어진 **5** x **5** 행렬을 만들고 이를 정규화해본다.

1. **randint()** 함수를 이용해 **1**부터 **100** 사이의 정수로 이루어진 행렬을 생성한다.
1. 행렬 내의 값들을 정규화한다.

- - -

**힌트**

$ \text{normalzed-value} = \frac{\text{value }-\text{ minvalue}} {\text{maxvalue }-\text{ minvalue}} $


In [ ]:
import numpy

# 임의의 정수로 이루어진 2차원 5 x 5 행렬을 생성한다.
arr = numpy.random.randint(1, 100, size=(5, 5))
arr

array([[73, 90, 43, 91,  9],
       [40, 69, 49,  8, 45],
       [ 1, 76, 56,  7, 20],
       [61, 45, 64, 70, 57],
       [25, 56, 54, 62, 65]])

In [ ]:
# 행렬 내의 값들을 정규화한다.
arrMax, arrMin = arr.max(), arr.min()
arr_normalized = (arr - arrMin) / (arrMax - arrMin)
arr_normalized

array([[0.8       , 0.98888889, 0.46666667, 1.        , 0.08888889],
       [0.43333333, 0.75555556, 0.53333333, 0.07777778, 0.48888889],
       [0.        , 0.83333333, 0.61111111, 0.06666667, 0.21111111],
       [0.66666667, 0.48888889, 0.7       , 0.76666667, 0.62222222],
       [0.26666667, 0.61111111, 0.58888889, 0.67777778, 0.71111111]])

- - -

# <font color='red'>THE END</font>